### ISSUE TITLE
Unable to Run Using Visual Studio 2019

### ISSUE THREAD

**Issue by sohail-karim** [andrewcanafe/miniftp-keylogger#2]
Brother I have tried several times to run this file in visual studio (2019) but i am unable to do so. can you please guide me. 
![Capture](https://user-images.githubusercontent.com/60038069/73155369-4b733880-40fc-11ea-9584-dc5eb9473363.PNG)

**Comment by andrewcanafe** [comment]
Hi, and thank you for commenting.

I don't recommend using Visual Studio 2019 for assembly language projects. At the moment, the keylogger code can only be compiled using my [MASM64 Custom SDK](https://github.com/andrewcanafe/MASM64-Custom-SDK).

If you want to learn how to compile the keylogger using ml64.exe and link.exe (tools installed with Visual Studio 2019), contact me through Discord. I can also teach you how to code in Windows assembly.

Discord username:
Firekaz#0390

**Comment by sohail-karim** [comment]
Thanks @andrewcanafe

**Comment by sohail-karim** [comment]
bro can you please help me to run this program

**Comment by andrewcanafe** [comment]
I will try to try to update the code in about a week so that it can be compiled using the VS 2019 built-in tools (ml64.exe and link.exe). Just have patience, my friend.

**Comment by andrewcanafe** [comment]
Code fixed. No longer crashes when compiling with VS 2019 built-in tools (ml64.exe and link.exe).
